import ROOT

ROOT.gROOT.SetBatch()

d = ROOT.RDataFrame("ZHCandidates", "source/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_2018UL.root")

c = ROOT.TCanvas()
upperPad = ROOT.TPad("upperPad", "", 0, 0.3, 1, 1)
lowerPad = ROOT.TPad("lowerPad", "", 0, 0, 1, 0.3)
nominal = d.Histo1D(ROOT.RDF.TH1DModel("nominal", "", 30, 50, 200), "higgs_mass", "z_sf")
upErr = d.Histo1D(ROOT.RDF.TH1DModel("upErr", "", 30, 50, 200), "higgs_mass", "z_sf_up")
downErr = d.Histo1D(ROOT.RDF.TH1DModel("downErr", "", 30, 50, 200), "higgs_mass", "z_sf_down")
origin = d.Histo1D(ROOT.RDF.TH1DModel("origin", "", 30, 50, 200), "higgs_mass")

c.Draw()
upperPad.Draw()
upperPad.SetBottomMargin(0)
lowerPad.Draw()
upperPad.cd()
origin.Draw()
#origin.GetXaxis().SetTitle("m_{#mu^{+} #mu^{-}} [GeV]")
origin.GetYaxis().SetTitle("A.U.")
#origin.SetMaximum(2.3e3)
#origin.SetMinimum(2e2)
origin.SetLineColor(ROOT.kBlack)
origin.SetLineStyle(2)
origin.SetStats(0)

nominal.Draw("hist same")
nominal.SetLineColor(ROOT.kRed)
upErr.Draw("hist same")
upErr.SetLineColor(ROOT.kAzure + 5)
downErr.Draw("hist same")
downErr.SetLineColor(ROOT.kOrange - 2)

leg = ROOT.TLegend(0.7, 0.7, 0.9, 0.9)
leg.AddEntry("origin", "W/O TnP SF", "L")
leg.AddEntry("nominal", "Nominal", "L")
leg.AddEntry("upErr", "+1#sigma", "L")
leg.AddEntry("downErr", "-1#sigma", "L")
leg.Draw()

lowerPad.cd()
lowerPad.SetTopMargin(0)
lowerPad.SetBottomMargin(0.3)
ratioUp = ROOT.TGraphAsymmErrors(upErr.Clone(), nominal.Clone(), "pois")
ratioDown = ROOT.TGraphAsymmErrors(downErr.Clone(), nominal.Clone(), "pois")
ratioUp.SetMarkerStyle(8)
ratioUp.SetMarkerColor(ROOT.kAzure + 5)
ratioDown.SetMarkerStyle(4)
ratioDown.SetMarkerColor(ROOT.kOrange - 2)
ratioMulti = ROOT.TMultiGraph()
ratioMulti.Add(ratioUp)
ratioMulti.Add(ratioDown)
ratioMulti.Draw("AP")
ratioMulti.GetXaxis().SetTitle("m_{b#bar{b}} [GeV]")
ratioMulti.GetXaxis().SetLimits(50, 200)
ratioMulti.GetXaxis().SetLabelSize(0.09)
ratioMulti.GetXaxis().SetTitleSize(0.12)
ratioMulti.GetYaxis().SetLabelSize(0.09)
ratioMulti.GetYaxis().SetNdivisions(505)
ratioMulti.GetYaxis().SetTitle("#pm 1#sigma/Nominal")
ratioMulti.GetYaxis().SetTitleSize(0.09)
ratioMulti.GetYaxis().SetTitleOffset(0.45)

intRatioUp = ROOT.TLatex()
intRatioDown = ROOT.TLatex()
intRatioUp.DrawLatexNDC(0.15, 0.9, "#sum +1#sigma/Nom. = {:.3f}".format(ratioUp.GetMean(2) * ratioUp.GetN()))
intRatioDown.DrawLatexNDC(0.28, 0.9, "#sum -1#sigma/Nom. = {:.3f}".format(ratioDown.GetMean(2) * ratioDown.GetN()))

c.SaveAs("compareTnP.pdf")

c2 = ROOT.TCanvas()
c2.Draw()
origin.Draw("][")
origin.GetXaxis().SetRangeUser(50, 100)
origin.GetXaxis().SetTitle("m_{b#bar{b}} [GeV]")
nominal.Draw("hist ][ same")
upErr.Draw("hist ][ same")
downErr.Draw("hist ][ same")
leg.Draw()
c2.SaveAs("compareTnP50to100.pdf")