import ROOT

ROOT.gROOT.SetBatch()
fAOD = ROOT.TFile("./AODHiggsXS.root")
fMG5EFTcpucpBB = ROOT.TFile("./mg5ZHBBXSEFT_cpu_cpBB.root")
fMG5EFT111 = ROOT.TFile("./mg5ZHBBXSEFT_cpW_cpWB_cpq3i.root")
fMG5EFT222 = ROOT.TFile("./mg5ZHBBXSEFT_cpW_cpWB_cpq3i_222.root")

hGen = fAOD.Get("genHiggsXS")
hMG5EFTcpucpBB = fMG5EFTcpucpBB.Get("mg5HiggsXSPt")
hMG5EFT111 = fMG5EFT111.Get("mg5HiggsXSPt")
hMG5EFT222 = fMG5EFT222.Get("mg5HiggsXSPt")

hGen.SetTitle("")
hGen.GetYaxis().SetTitle("d#sigma / dp_{T} [fb/N GeV]")
hGen.GetYaxis().SetTitleSize(0.05)
hGen.GetYaxis().SetLabelSize(0.055)
#hGen.GetYaxis().SetRangeUser(0, 1.2)
hGen.GetYaxis().SetTitleOffset(0.8)
hGen.SetStats(0)
hGen.SetMarkerStyle(32)
hGen.SetLineColor(ROOT.kRed)
hGen.SetMarkerColor(ROOT.kRed)

hMG5EFT111.SetStats(0)
hMG5EFT111.SetMarkerStyle(28)
hMG5EFT111.SetMarkerColor(ROOT.kBlack)
hMG5EFT111.SetLineColor(ROOT.kBlack)
#hMG5EFT111.GetYaxis().SetRangeUser(0, 1.5)

hMG5EFT222.SetStats(0)
hMG5EFT222.SetMarkerStyle(46)
hMG5EFT222.SetMarkerColor(ROOT.kTeal + 5)
hMG5EFT222.SetLineColor(ROOT.kTeal + 5)
#hMG5EFT222.GetYaxis().SetRangeUser(0, 1.5)

# hMG5EFTcpucpBB.GetYaxis().SetTitle("Nevents")
hMG5EFTcpucpBB.SetStats(0)
hMG5EFTcpucpBB.SetMarkerStyle(26)
hMG5EFTcpucpBB.SetMarkerColor(ROOT.kBlue)
hMG5EFTcpucpBB.SetLineColor(ROOT.kBlue)
#hMG5EFTcpucpBB.GetYaxis().SetRangeUser(0, 1.5)

c = ROOT.TCanvas()
upperPad = ROOT.TPad("upperPad", "upperPad", 0., 0.3, 1., 1.)
lowerPad = ROOT.TPad("lowerPad","lowerPad", 0., 0., 1., 0.3)
upperPad.Draw()
lowerPad.Draw()
upperPad.SetTicks(1, 1)
upperPad.SetLogy()
upperPad.SetBottomMargin(0.)
#upperPad.SetRightMargin(0.2)
hGen.SetMinimum(3e-4)
#hGen.SetMaximum(50)
upperPad.cd()

hGen.Draw("h")
hMG5EFTcpucpBB.Draw("peh same")
hMG5EFT111.Draw("peh same")
hMG5EFT222.Draw("peh same")
lowerPad.cd()
lowerPad.SetTicks(1, 1)
lowerPad.SetGridy()
lowerPad.SetTopMargin(0.)
lowerPad.SetBottomMargin(0.3)
hRatiocpucpBB = ROOT.TGraphAsymmErrors()
hRatiocpucpBB.Divide(hMG5EFTcpucpBB, hGen, 'pois')
hRatiocpucpBB.SetMarkerStyle(26)
hRatiocpucpBB.SetMarkerColor(ROOT.kBlue)
hRatiocpucpBB.SetLineColor(ROOT.kBlue)

hRatiocpWcpWBcpq3i = ROOT.TGraphAsymmErrors()
hRatiocpWcpWBcpq3i.Divide(hMG5EFT111, hGen, 'pois')
hRatiocpWcpWBcpq3i.SetMarkerStyle(28)
hRatiocpWcpWBcpq3i.SetMarkerColor(ROOT.kBlack)
hRatiocpWcpWBcpq3i.SetLineColor(ROOT.kBlack)

hRatiocpWcpWBcpq3i222 = ROOT.TGraphAsymmErrors()
hRatiocpWcpWBcpq3i222.Divide(hMG5EFT222, hGen, 'pois')
hRatiocpWcpWBcpq3i222.SetMarkerStyle(46)
hRatiocpWcpWBcpq3i222.SetMarkerColor(ROOT.kTeal + 5)
hRatiocpWcpWBcpq3i222.SetLineColor(ROOT.kTeal + 5)

hRatioMulti = ROOT.TMultiGraph("hRatioMulti", "")
hRatioMulti.Add(hRatiocpucpBB, "AP")
hRatioMulti.Add(hRatiocpWcpWBcpq3i, "AP")
hRatioMulti.Add(hRatiocpWcpWBcpq3i222, "AP")

hRatioMulti.GetXaxis().SetTitleSize(0.13)
hRatioMulti.GetXaxis().SetLabelSize(0.13)
hRatioMulti.GetXaxis().SetTitleOffset(1)
hRatioMulti.GetXaxis().SetLimits(0, 500)
hRatioMulti.GetXaxis().SetTitle("p_{T}^{Higgs} [GeV]")
hRatioMulti.GetYaxis().SetNdivisions(505)
hRatioMulti.GetYaxis().SetRangeUser(0.7, 2)
hRatioMulti.GetYaxis().SetTitle("#frac{EFT}{POWHEG V2}")
hRatioMulti.GetYaxis().SetTitleSize(0.1)
hRatioMulti.GetYaxis().SetLabelSize(0.13)
hRatioMulti.GetYaxis().SetTitleOffset(0.4)
hRatioMulti.Draw("AP")

upperPad.cd()
leg = ROOT.TLegend(0.13, 0.05, 0.38, 0.6)
#leg = ROOT.TLegend(0.3, 0.5, 0.83, 0.85)
leg.SetBorderSize(0)
leg.AddEntry(hGen, "POWHEG V2 (NLO, SM)", "PE")
leg.AddEntry(hMG5EFTcpucpBB, "#splitline{MG5_SMEFT@NLO + Pythia8}{cpu=cpBB=0.1}", "PE")
leg.AddEntry(hMG5EFT111, "#splitline{MG5_SMEFT@NLO + Pythia8}{cpW=cpWB=cpq3i=0.1}", "PE")
leg.AddEntry(hMG5EFT222, "#splitline{MG5_SMEFT@NLO + Pythia8}{cpW=cpWB=cpq3i=0.2}", "PE")
'''
leg.AddEntry(hRatiocpucpBB, "cpu=cpBB=0.1/SM", "PE")
leg.AddEntry(hRatiocpWcpWBcpq3i, "cpW=cpWB=cpq3i=0.1/SM", "PE")
leg.AddEntry(hRatiocpWcpWBcpq3i222, "cpW=cpWB=cpq3i=0.2/SM", "PE")
#leg.SetNColumns(2)
'''
leg.SetTextSize(0.04)
leg.Draw("same")

c.SaveAs("./ratio_logy.pdf")