import ROOT

ROOT.gROOT.SetBatch()
fAOD = ROOT.TFile("./AODHiggsXS.root")
fMG5 = ROOT.TFile("./mg5ZHBBXS.root")
fMG5EFT111 = ROOT.TFile("./mg5ZHBBXSEFTcpW_111.root")
fMG5EFTctG = ROOT.TFile("./mg5ZHBBXSEFTctG.root")
fMG5EFT222 = ROOT.TFile("./mg5ZHBBXSEFTcpW_222.root")

hGen = fAOD.Get("genHiggsXS")
hMG5 = fMG5.Get("mg5HiggsXSPt")
hMG5EFT111 = fMG5EFT111.Get("mg5HiggsXSPt")
hMG5EFTctG = fMG5EFTctG.Get("mg5HiggsXSPt")
hMG5EFT222 = fMG5EFT222.Get("mg5HiggsXSPt")

hGen.SetTitle("")
hGen.GetYaxis().SetTitle("d#sigma / dp_{T} [fb/N GeV]")
hGen.SetStats(0)
hGen.SetMarkerStyle(32)
hGen.SetLineColor(ROOT.kRed)
hGen.SetMarkerColor(ROOT.kRed)

hMG5.SetStats(0)
hMG5.SetMarkerStyle(24)
hMG5.SetMarkerColor(ROOT.kSpring + 2)
hMG5.SetLineColor(ROOT.kSpring + 2)

hMG5EFT111.SetStats(0)
hMG5EFT111.SetMarkerStyle(28)
hMG5EFT111.SetMarkerColor(ROOT.kViolet - 4)
hMG5EFT111.SetLineColor(ROOT.kViolet - 4)

hMG5EFT222.SetStats(0)
hMG5EFT222.SetMarkerStyle(46)
hMG5EFT222.SetMarkerColor(ROOT.kViolet + 4)
hMG5EFT222.SetLineColor(ROOT.kViolet + 4)

# hMG5EFTctG.GetYaxis().SetTitle("Nevents")
hMG5EFTctG.SetStats(0)
hMG5EFTctG.SetMarkerStyle(26)
hMG5EFTctG.SetMarkerColor(ROOT.kAzure + 4)
hMG5EFTctG.SetLineColor(ROOT.kAzure + 4)

c = ROOT.TCanvas()
upperPad = ROOT.TPad("upperPad", "upperPad", 0., 0.3, 1., 1.)
lowerPad = ROOT.TPad("lowerPad","lowerPad", 0., 0., 1., 0.3)
upperPad.Draw()
lowerPad.Draw()
upperPad.SetTicks(1, 1)
upperPad.SetLogy()
upperPad.SetBottomMargin(0.)
upperPad.SetTopMargin(0.2)
#hGen.SetMinimum(3e-9)
hGen.SetMaximum(10)
upperPad.cd()

hGen.Draw()
hMG5EFTctG.Draw("pe same")
hMG5.Draw("pe same")
hMG5EFT111.Draw("pe same")
hMG5EFT222.Draw("pe same")
lowerPad.cd()
lowerPad.SetTicks(1, 1)
lowerPad.SetGridy()
lowerPad.SetTopMargin(0.)
lowerPad.SetBottomMargin(0.3)
hRatioctG = ROOT.TGraphAsymmErrors()
hRatioctG.Divide(hMG5EFTctG, hGen, 'pois')
hRatioctG.SetMarkerStyle(22)
hRatioctG.SetMarkerColor(ROOT.kAzure + 4)
hRatioctG.SetLineColor(ROOT.kAzure + 4)

hRatiocpW = ROOT.TGraphAsymmErrors()
hRatiocpW.Divide(hMG5EFT111, hGen, 'pois')
hRatiocpW.SetMarkerStyle(34)
hRatiocpW.SetMarkerColor(ROOT.kViolet - 4)
hRatiocpW.SetLineColor(ROOT.kViolet - 4)

hRatiocpW222 = ROOT.TGraphAsymmErrors()
hRatiocpW222.Divide(hMG5EFT222, hGen, 'pois')
hRatiocpW222.SetMarkerStyle(47)
hRatiocpW222.SetMarkerColor(ROOT.kViolet + 4)
hRatiocpW222.SetLineColor(ROOT.kViolet + 4)

hRatioMulti = ROOT.TMultiGraph("hRatioMulti", "")
hRatioMulti.Add(hRatioctG, "AP")
hRatioMulti.Add(hRatiocpW, "AP")
hRatioMulti.Add(hRatiocpW222, "AP")

hRatioMulti.GetXaxis().SetTitleSize(0.1)
hRatioMulti.GetXaxis().SetLabelSize(0.08)
hRatioMulti.GetXaxis().SetTitleOffset(1)
hRatioMulti.GetXaxis().SetLimits(0, 500)
hRatioMulti.GetXaxis().SetTitle("p_{T}^{Higgs} [GeV]")
hRatioMulti.GetYaxis().SetNdivisions(505)
hRatioMulti.GetYaxis().SetRangeUser(0.2, 1.6)
hRatioMulti.GetYaxis().SetTitle("#frac{EFT}{PowHegV2}")
hRatioMulti.GetYaxis().SetTitleSize(0.08)
hRatioMulti.GetYaxis().SetLabelSize(0.08)
hRatioMulti.GetYaxis().SetTitleOffset(0.4)
hRatioMulti.Draw("AP")

upperPad.cd()
leg = ROOT.TLegend(0.01, 0.85, 0.99, 0.99)
leg.SetBorderSize(0)
leg.AddEntry(hGen, "PowHegV2", "PE")
leg.AddEntry(hMG5EFTctG, "MG5_SMEFT@NLO + Pythia8 ctG=cpq3i=1", "PE")
leg.AddEntry(hMG5, "MG5 + Pythia8", "PE")
leg.AddEntry(hMG5EFT111, "MG5_SMEFT@NLO + Pythia8 cpW=cpWB=cpq3i=1", "PE")
leg.AddEntry(hMG5EFT222, "MG5_SMEFT@NLO + Pythia8 cpW=cpWB=cpq3i=2", "PE")
leg.AddEntry(hRatioctG, "ctG=cpq3i=1/SM", "PE")
leg.AddEntry(hRatiocpW, "cpW=cpWB=cpq3i=1/SM", "PE")
leg.AddEntry(hRatiocpW222, "cpW=cpWB=cpq3i=2/SM", "PE")
leg.SetNColumns(4)
leg.SetTextSize(0.02)
leg.Draw("same")

c.SaveAs("./ratio.pdf")