import ROOT

ROOT.gROOT.SetBatch()
fAOD = ROOT.TFile("./AODHiggsXS.root")
fMG5 = ROOT.TFile("./mg5ZHBBXS.root")
fMG5EFT = ROOT.TFile("./mg5ZHBBXSEFT.root")

hGen = fAOD.Get("genHiggsXS")
hReco = fAOD.Get("recoHiggsXS")
hMG5 = fMG5.Get("mg5HiggsXSPt")
hMG5EFT = fMG5EFT.Get("mg5HiggsXSPt")

hGen.SetTitle("")
hGen.GetYaxis().SetTitle("d#sigma / dp_{T} [fb/GeV]")
hGen.SetStats(0)
hGen.SetMarkerStyle(32)
hGen.SetLineColor(ROOT.kRed)
hGen.SetMarkerColor(ROOT.kRed)

# hReco.GetYaxis().SetTitle("Nevents")
hReco.SetStats(0)
hReco.SetMarkerStyle(26)
hReco.SetMarkerColor(ROOT.kAzure + 4)
hReco.SetLineColor(ROOT.kAzure + 4)

hMG5.SetStats(0)
hMG5.SetMarkerStyle(24)
hMG5.SetMarkerColor(ROOT.kSpring + 2)
hMG5.SetLineColor(ROOT.kSpring + 2)

hMG5EFT.SetStats(0)
hMG5EFT.SetMarkerStyle(28)
hMG5EFT.SetMarkerColor(ROOT.kViolet - 4)
hMG5EFT.SetLineColor(ROOT.kViolet - 4)

c = ROOT.TCanvas()
upperPad = ROOT.TPad("upperPad", "upperPad", 0., 0.3, 1., 1.)
lowerPad = ROOT.TPad("lowerPad","lowerPad", 0., 0., 1., 0.3)
upperPad.Draw()
lowerPad.Draw()
upperPad.SetTicks(1, 1)
upperPad.SetLogy()
upperPad.SetBottomMargin(0.)
#hGen.SetMinimum(3e-9)
hGen.SetMaximum(10)
upperPad.cd()
cmsTag = ROOT.TLatex(0.13, 0.917, "#scale[1.1]{CMS}")
cmsTag.SetNDC()
cmsTag.SetTextAlign(11)
cmsTag2 = ROOT.TLatex(0.2, 0.917, "#scale[0.825]{#bf{#it{Private}}}")
cmsTag2.SetNDC()
cmsTag2.SetTextAlign(11)
cmsTag3 = ROOT.TLatex(
	0.90, 0.917, "#scale[0.9]{#bf{59.83 fb^{-1} (13 TeV, 2018)}}")
cmsTag3.SetNDC()
cmsTag3.SetTextAlign(31)
hGen.Draw()
hReco.Draw("same")
hMG5.Draw("pe same")
hMG5EFT.Draw("pe same")
cmsTag.Draw("same")
cmsTag2.Draw("same")
cmsTag3.Draw("same")
lowerPad.cd()
lowerPad.SetTicks(1, 1)
lowerPad.SetGridy()
lowerPad.SetTopMargin(0.)
lowerPad.SetBottomMargin(0.3)
hRatio = ROOT.TGraphAsymmErrors()
hRatio.Divide(hReco, hGen, 'pois')
hRatio.GetXaxis().SetTitleSize(0.1)
hRatio.GetXaxis().SetLabelSize(0.08)
hRatio.GetXaxis().SetTitleOffset(1)
hRatio.GetXaxis().SetLimits(0, 500)
hRatio.GetXaxis().SetTitle("p_{T}^{Dijet} [GeV]")
hRatio.GetYaxis().SetNdivisions(505)
hRatio.GetYaxis().SetRangeUser(0.2, 1.6)
hRatio.GetYaxis().SetTitle("#frac{PFJets}{GenParticle}")
hRatio.GetYaxis().SetTitleSize(0.08)
hRatio.GetYaxis().SetLabelSize(0.08)
hRatio.GetYaxis().SetTitleOffset(0.4)
hRatio.SetMarkerStyle(21)
hRatio.Draw("AP")

upperPad.cd()
leg = ROOT.TLegend(0.35, 0.65, 0.86, 0.87)
leg.SetBorderSize(0)
leg.AddEntry(hGen, "prunedGenParticle", "PE")
leg.AddEntry(hReco, "PFJet", "PE")
leg.AddEntry(hMG5, "MG5 + Pythia8", "PE")
leg.AddEntry(hMG5EFT, "MG5_SMEFT@NLO + Pythia8", "PE")
leg.AddEntry(hRatio, "Ratio", "PE")
leg.SetNColumns(3)
leg.SetTextSize(0.04)
leg.Draw("same")

c.SaveAs("./ratio.pdf")